### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by swaytz** [ostigter/secs4j#2]
Hallo,
When I try to run the code as is, I get the following error:
Internal error while sending message
java.net.SocketException: Software caused connection abort: socket write error
The point of failure is at the sendMessage() function in SecsEquipment.
Is the given code functional?

**Comment by ostigter** [comment]
Hi swaytz,

This project has been inactive for many years and I doubt I'll ever look into it again.

Feel free to reverse-engineer the code and reuse what you need.  I remember leaving it in a working state, at least the unit tests (e.g. with "mvn test")..

Kind regards,
Oscar
