### ISSUE TITLE
How can I learn about it?

### ISSUE THREAD

**Issue by gt2ming** [ostigter/secs4j#4]
Hello dear author,
I am a beginner in SECS/GEM protocol,
After reading your work: secs4j,
I would like to learn more,
But I can't find any suitable material on the web,
How can I learn about it?
Looking forward to the answer!

**Comment by ostigter** [comment]
Hi,

Thanks for checking out my old secs4j project!

Back then, I also had a hard time finding material online. I've learned it the hard way from the official SECS/GEM protocol papers from the SEMI organization and reverse-engineering a commercial, third-party SECS/GEM library, both of which my employer has commercial licenses/subscriptions for. You'll understand I cannot distribute those.

You can of course reverse-engineer my sources, but as the README says, it's only a very basic and partial SECS/GEM implementation, covering only the most core functions. You would definitely need the full protocol spec and preferably some real SECS devices (or simulating software) to test against. It seems if you really want to learn/use SECS/GEM, you'll have to invest in it, like getting a SEMI subscription. I think it's a pretty vendor-locked, specific software corner.

Hope this helps.

Regards,
Oscar

**Comment by gt2ming** [comment]
Thank you for your reply.

I understand what you are saying about the licensing issue.

In fact, what confuses me is that I don't know how to go about learning this part.

In detail, it's that I don't know the path to learn.

Your reply helped me a lot, thanks.

I hope I can continue to ask you for advice in the future.
